# Multi-H100 GPU VM Configuration
name: mot-h100-multi
machine_type: n1-standard-32
gpu_type: nvidia-h100-80gb
gpu_count: 4
zone: us-central1-a
boot_disk_size: 300
training_config: configs/training/large_multigpu.yaml

# Cost: ~$20.00/hour (4x H100)
# 4x faster training than single GPU
