# Medium model - fits V100 16GB (~2-4 hours)
train_file: data/shakespeare.txt
vocab_size: 50257
hidden_size: 512
num_layers: 6
num_thoughts: 8
batch_size: 8
num_epochs: 20
learning_rate: 0.0001
diversity_weight: 0.1
entropy_weight: 0.05
output_dir: outputs/medium_run
